name: Android CI

on:
  push:
    branches: [ master, recyclerview ]
  pull_request:
    branches: [ master, recyclerview ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Change wrapper permissions
      run: chmod +x ./gradlew 
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
  apk: 
    name: APK Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assemble app debug APK
        run: bash ./gradlew :app:assembleDebug
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Assemble app debug APK
        run: bash ./gradlew :app:assembleDebug
  lint:
    name: Lint Check
#     needs: build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint debug flavor
        run: bash ./gradlew lintDebug --stacktrace
      - name: Lint results
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/reports/lint-results-debug.html        
          
  pushbullet: 
      name: pushbullet
      needs: build
      runs-on: ubuntu-latest
      steps: 
      - uses: ShaunLWM/action-pushbullet@master
      env:
        PB_TOKEN: ${{ secrets.PUSH_KEY }}
        PB_TITLE: Build Complete
        PB_TEXT: Your project has been built.

